### ISSUE TITLE
Comment utiliser l'outil ?

### ISSUE THREAD

**Issue by COLIBRI-BIRD** [lesensei/aioze#1]
Bonjour,
Cette outil m'intéresse mais comment l'utiliser ?

**Comment by lesensei** [comment]
Mes excuses, je n'avais pas vu ce "bogue" avant aujourd'hui.
Malheureusement, le département dans lequel je réside a changé d'ENT cette année et je n'ai plus d'environnement dans lequel je vais pouvoir tester la bibliothèque pour la maintenir en état de fonctionnement. Dans ces conditions, on peut déjà considérer qu'elle est abandonnée (et j'archiverai sans doute le dépôt prochainement) :-(

Pour tenter tout de même de répondre, voici un exemple pour récupérer la liste des notes de chaque élève rattaché à un compte parent dans Oze:
```python
from aioze import OzeApiClient

async def main():
    url = "https://enc.domaine.fr/"
    username = "utilisateur@domaine.fr"
    password = 'motdepasse'
    session = aiohttp.ClientSession()

    client = OzeApiClient(url, username, password, session)
    conn = await client.connect()
    user_info = await client.userinfo.get_user_info()
    pupils = client.userinfo.get_pupils_from_userinfo(user_info)
    for pupil in pupils:
        grades = await client.grade.get_grades(pupil)
```
